runtime: python311

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

env_variables:
  FLASK_ENV: "production"
  USE_REAL_AI: "true"
  SESSION_TIMEOUT_MINUTES: "15"
  DATA_RETENTION_YEARS: "7"

# Note: Set sensitive environment variables using Secret Manager
# Do not put API keys or encryption keys in this file

handlers:
- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# Enable Cloud SQL (uncomment and configure for production)
# beta_settings:
#   cloud_sql_instances: YOUR_PROJECT:YOUR_REGION:YOUR_INSTANCE

# Health checks
readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/api/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

